---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
  - name: check
    image: quay.io/sighup/katalog:1.0.10_3
    command:
      - ./generate_dockerfiles.py
      - git diff --quiet HEAD

  - name: build
    image: docker:dind
    environment:
      USER:
        from_secret:
          QUAY_USER
      TOKEN:
        from_secret:
          QUAY_TOKEN
    pull: always
    commands:
      - docker login -p $TOKEN -u $USER quay.io
      - apk add --no-cache python3 py-yaml
      - ./build.py quay.io
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    when:
      event:
      - push
      branch:
      - master

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
