---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
  - name: integration-test
    image: docker:dind
    pull: always
    commands:
      - apk add --no-cache python3
      - pip install pyyaml
      - ./build.py
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    when:
      event:
      - push

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
